### PR TITLE
Change JacobiWeight Conversion

### PR DESCRIPTION
**Pull request by putianyi889**
Changed the routine of the conversion. Not sure if it works as I rewrote all codes.

`A=JacobiWeight(2,0,Jacobi(2,-2))`
`B=Legendre()`

Before change:
`Conversion(A,B)=Conversion(A,JacobiWeight(0,0,Jacobi(0,-2)),B)`
where `Conversion(JacobiWeight(0,0,Jacobi(0,-2)),Legendre())` is not well-defined (has some `NaN`s)

After change:
`Conversion(A,B)=Conversion(A,JacobiWeight(2,0,Jacobi(2,0)),B)`

The example has been added to test.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
The tests are failing

**Comment by putianyi889** [comment]
It passed old tests, though. I don't know why a syntax error was thrown. I tested the codes step by step on my computer but it works fine.

**Comment by dlfivefifty** [comment]
You can run the tests on your machine via ` ] test ApproxFunSingularities `

**Comment by putianyi889** [comment]
Shall I edit the codes in `package` or `dev` folder?

**Comment by putianyi889** [comment]
AppVeyor is actually faster than my computer XD so I'm gonna stick to it.
BTW the last test passed. I only slighted changed the test to an equivalent one. I have no idea why the old one threw an error.

**Pull request closed without merging**
